### ISSUE TITLE
Provide maven artifact and repo

### ISSUE THREAD

**Issue by Phoenix616** [jojodmo/ItemBridge#1]
Currently it's really hard to depend on this plugin so it would be pretty nice if you could provide a maven artifact and repo. Easiest would be via github's packages or, if you don't want to build it yourself, at least provide a maven pom/gradle project to be able to automatically build it and install it to some repo.

**Comment by mrrhetorical** [comment]
@Phoenix616 It's not really necessary right now, you can just use [jitpack.io](https://jitpack.io/#jojodmo/ItemBridge/master-SNAPSHOT) to grab the maven dependency.

**Comment by Phoenix616** [comment]
You can't really as you don't provide any kind of build information in this repo. Jitpack can't magically build stuff without info about dependencies etc.

**Comment by mrrhetorical** [comment]
After posting and trying to do so myself, I realized that. I created a pull request that I'm hoping @jojodmo will accept that changes the project to a Maven project and should allow for it to be used with jitpack.

**Comment by jojodmo** [comment]
Thank you @mrrhetorical for the pull request! I merged it and made a few minor changes, and so you can now use https://jitpack.io/#jojodmo/ItemBridge to add ItemBridge as a Maven dependency
